-- Photographic evidence for a failed inspection item.
--
-- Background
--
-- A failed checklist item names a fault. It cannot describe one. A mechanic reading
-- "Door seal" on a work order learns that the seal was marked failed and nothing about
-- whether it is perished or torn away, and the difference decides whether the bus waits
-- for a part. A photograph taken at the moment of the failure carries what the label
-- cannot, and it is the one part of an inspection that cannot be produced by somebody who
-- never walked around the bus.
--
-- Photographs are optional. A fuel level below the mark needs none; a cracked mirror does.
-- Requiring one on every failure would collect pictures of dashboards and teach drivers to
-- dismiss the prompt.
--
-- Evidence only. Nothing here reaches the decision to ground a bus, which is made from
-- checklist_items alone and belongs to the server.
--
-- Model
--
-- A photograph belongs to the inspection that produced it, not to the maintenance line it
-- raises. A fault reported again reopens the line it already has rather than starting a
-- second one, so one line accumulates inspections across its life, and a photograph held
-- on the line would be overwritten by each new sighting of the same fault. What a mechanic
-- most wants from a fault that has come back is whether it looks worse than last time,
-- which is the comparison that overwriting destroys.
--
-- The maintenance order is recorded alongside, though it is reachable through the item.
-- Reading a vehicle's photographs and deciding which ones have aged out are the two ways
-- this table is used, and both ask about the order, so carrying it turns each into one
-- join rather than a walk through the vehicle.
--
-- Identity
--
-- The object is named by the device, before the inspection is submitted and therefore
-- before checklist_id exists. The name is generated when a photograph is first attached to
-- an item and reused if it is retaken, so a retake overwrites rather than accumulating.
-- This is the reasoning already applied to boarding_events: an identifier fixed at the
-- moment of the event means a resend stores once, and the server never reconstructs a name
-- from state it might read differently.
--
-- Naming the object after the trip would not be safe. bus_checklist has no unique
-- constraint on trip_id, so a submit that timed out after the server had committed, then
-- was retried, leaves one trip holding two inspections that would claim one object.
--
-- Retention
--
-- Photographs are kept while their work order is open and for thirty days after it closes.
-- The grace period exists because a fault closed and reopened inside the month is exactly
-- the case the history was kept for.
--
-- Sweeping clears object_key and stamps swept_at, leaving the row. Deleting the row would
-- be tidier and would lie: a line that never had a photograph and a line whose photograph
-- aged out would read identically, and those are different facts about how the fleet was
-- run.

begin;

create table if not exists public.inspection_photos (
  photo_id          bigint generated by default as identity,
  checklist_id      integer not null,
  checklist_item_id bigint  not null,
  log_id            integer,
  object_key        text,
  taken_at          timestamptz not null,
  uploaded_at       timestamptz not null default now(),
  swept_at          timestamptz,

  constraint pk_inspection_photos primary key (photo_id),
  constraint fk_inspection_photos_checklist
    foreign key (checklist_id) references public.bus_checklist (checklist_id) on delete cascade,
  constraint fk_inspection_photos_item
    foreign key (checklist_item_id) references public.checklist_items (item_id),
  constraint fk_inspection_photos_log
    foreign key (log_id) references public.maintenance_logs (log_id) on delete set null,
  constraint ck_inspection_photos_swept
    check ((object_key is null) = (swept_at is not null))
);

comment on table public.inspection_photos is 'A photograph of a failed inspection item. Evidence for a fault, never the decision about one.';

comment on column public.inspection_photos.checklist_id is 'The inspection this was taken during. Cascades, because a photograph of an inspection that no longer exists describes nothing.';

comment on column public.inspection_photos.checklist_item_id is 'The item that failed. What a work order line matches on to gather its photographs.';

comment on column public.inspection_photos.log_id is 'The order this fault was raised onto, carried so retention and reading need no walk through the vehicle. Nulled rather than cascaded if the order goes, since the photograph is still evidence of the inspection.';

comment on column public.inspection_photos.object_key is 'Path in the inspection-photos bucket, named by the device. Null once the photograph has been swept, which the check constraint ties to swept_at.';

comment on column public.inspection_photos.taken_at is 'When the photograph was taken, by the device clock.';

comment on column public.inspection_photos.uploaded_at is 'When the row was recorded, after the object was confirmed present.';

comment on column public.inspection_photos.swept_at is 'When the object was deleted under the retention rule. The row survives so that a photograph that aged out stays distinguishable from one that was never taken.';

-- Gathering a vehicle's photographs and ageing them out both start from the order.
create index if not exists ix_inspection_photos_log
  on public.inspection_photos (log_id);

-- A work order line gathers its own photographs by the item that raised it.
create index if not exists ix_inspection_photos_item
  on public.inspection_photos (checklist_item_id);

-- ---------------------------------------------------------------------------
-- Access
-- ---------------------------------------------------------------------------

-- Row level security with no policy for any device role, which is the intent rather than
-- an omission. Rows are written by inspection-submit and read by the dashboard, both
-- holding the service key, which row level security does not apply to. The driver app
-- never touches this table: it writes the object to storage and names it at submit, and
-- the server decides what is recorded.
alter table public.inspection_photos enable row level security;

-- ---------------------------------------------------------------------------
-- Storage
-- ---------------------------------------------------------------------------

-- Private, so nothing is readable without a key. The dashboard proxies reads through the
-- web server exactly as it does for camera snapshots.
--
-- The size and type limits are the bucket's own, enforced by the storage API ahead of row
-- level security. They are the two checks an upload proxy would have been written to
-- perform, which is the reason no such proxy exists: a driver can write only under their
-- own identity, only JPEG, and only small, without a second upload mechanism in a codebase
-- that already has one.
--
-- 512 KB against a target of roughly 200 KB for 1280 px at quality 75, so a slightly
-- larger camera does not start refusing photographs.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('inspection-photos', 'inspection-photos', false, 524288, array['image/jpeg'])
on conflict (id) do update
  set public            = excluded.public,
      file_size_limit   = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Objects are stored at inspection-photos/<driver_id>/<uuid>.jpg. The name is the identity
-- and the folder carries no meaning of its own: it exists so the policy below has
-- something to check, since a bare identifier tells a policy nothing about who may write
-- it.
--
-- The schema grant is stated rather than assumed. app_camera reaches this same table for
-- its snapshots, so the privilege exists for that role, and nothing records whether
-- app_driver was ever given it.
grant usage on schema storage to app_driver;
grant select, insert, update, delete on storage.objects to app_driver;

-- Select is granted for the sake of the write, as it is on boarding_events. Replacing an
-- object is an upsert, which must first decide whether one is already there, and under row
-- level security a row nothing can see does not exist. Without select a retake is refused
-- for want of a privilege the request never appears to use.
drop policy if exists p_inspection_photo_driver_select on storage.objects;
create policy p_inspection_photo_driver_select on storage.objects
  for select to app_driver
  using (
    bucket_id = 'inspection-photos'
    and (storage.foldername(name))[1] = public.jwt_uid()::text
  );

drop policy if exists p_inspection_photo_driver_insert on storage.objects;
create policy p_inspection_photo_driver_insert on storage.objects
  for insert to app_driver
  with check (
    bucket_id = 'inspection-photos'
    and (storage.foldername(name))[1] = public.jwt_uid()::text
  );

-- Retaking replaces the object under the same name.
drop policy if exists p_inspection_photo_driver_update on storage.objects;
create policy p_inspection_photo_driver_update on storage.objects
  for update to app_driver
  using (
    bucket_id = 'inspection-photos'
    and (storage.foldername(name))[1] = public.jwt_uid()::text
  )
  with check (
    bucket_id = 'inspection-photos'
    and (storage.foldername(name))[1] = public.jwt_uid()::text
  );

-- A driver who marks an item Pass again, or removes the photograph, deletes the object
-- they uploaded. That is the only cleanup that happens at the moment it is needed: an
-- inspection abandoned outright leaves an object nothing points at, which the documented
-- orphan sweep removes.
drop policy if exists p_inspection_photo_driver_delete on storage.objects;
create policy p_inspection_photo_driver_delete on storage.objects
  for delete to app_driver
  using (
    bucket_id = 'inspection-photos'
    and (storage.foldername(name))[1] = public.jwt_uid()::text
  );

commit;
